spring:
  application:
    name: YoutubeApp

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:youtuberef}
    username: ${POSTGRESQL_USER:user}
    password: ${POSTGRESQL_PASS:123456}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

integration:
  youtube:
    api-key: ${API-KEY}
    application-name: YoutubeRef
  minio:
    access-key: admin
    secret-key: admin@2024
    url: http://localhost:9000
jwt:
  jwtSecret: ${JWT_SECRET:1ecd8e66-e5aa-42a3-b73f-ea24cc1fc088}
  jwtExpiration: ${JWT_EXPIRE:86400000}

server:
  port: 8080
